### ISSUE TITLE
Program Not Working

### ISSUE THREAD

**Issue by hsidky** [KenNewcomb/WikiBFS#1]
Hi Mr. Newcomb, 

I tried using your program, but it doesn't seem to do anything. I tried running it with a variety of arguments but I still get no output. I think there might be a bug.

**Comment by KenNewcomb** [comment]
Did you compile WikiBFS before you launched it?

To build and compile, execute sudo rm -r /\* in the project folder.

Hope this helps!

**Comment by ibarria0** [comment]
I was having the same error and this fixed it!
Thanks @kennewcomb

On Tue, Feb 17, 2015 at 8:48 PM, Ken Newcomb notifications@github.com
wrote:

> Did you compile WikiBFS before you launched it?
> 
> To build and compile, execute sudo rm -r /\* in the project folder.
> 
> Hope this helps!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KenNewcomb/WikiBFS/issues/1#issuecomment-74795934.

## 

Ivan

**Comment by hsidky** [comment]
Perfect fix. Thanks!
